name: pfoten
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
#  blobs: ^2.0.0
  sizer: ^2.0.15
#  shrink_sidemenu: ^2.0.0+2-null-safety
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  animated_bottom_navigation_bar: ^0.3.2
  auto_size_text: ^3.0.0
  animations: ^2.0.2
  sliding_switch: ^1.0.0
  syncfusion_flutter_datepicker: ^19.4.56
  weekday_selector: ^1.1.0
  expandable: ^5.0.1
  date_picker_timeline: ^1.2.3

#  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: IndieFlower
      fonts:
        - asset: fonts/indie/IndieFlower-Regular.ttf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf

    - family: RobotoSlab
      fonts:
        - asset: fonts/robotoSlab/RobotoSlab-VariableFont_wght.ttf